### ISSUE TITLE
webui: builds stack without the command runner

### ISSUE THREAD

**Issue by tupakkatapa** [ponkila/HomestakerOS#23]
Build commands will stack until the command runner is opened. This is not the expected behavior in my opinion.

To reproduce:

  1. Start the server without the command runner

  2. Hit the build button a couple of times

  3. Start the command runner in terminal by executing `tail -f pipe | sh`

**Comment by tupakkatapa** [comment]
I discovered a new aspect about this. If build commands are stacked before launching the command runner and the command runner is started (stacked commands will run) and then restarted, it will execute the stacked build commands again. So, the front end stores them and does not let go of the stack even if they are executed once.

**Comment by jhvst** [comment]
This is more to do with how pipes work. This is essentially a no-fix. FIFO implies this in the name: first in, first out.
