### ISSUE TITLE
webui: infinite loading of the boot files

### ISSUE THREAD

**Issue by tupakkatapa** [ponkila/HomestakerOS#25]
The "Nodes" tab will display continuous loading icons for each of the boot files.

**Comment by tupakkatapa** [comment]
Regarding this feature, I believe it should be entirely dynamic, capable of handling any files that appear in the result folder. For instance, if we choose to package the kernel, ramdisk, and kexec-script into a archive for single download only, it should be able to manage it. Additionally, since we plan to provide a choice between the `isoImage` and `kexecTree` output formats, it should be able to handle that as well.

I would like to hear @jhvst's opinion on this.

**Comment by tupakkatapa** [comment]
P.S. I tried adding the '-r' flag to the build command to resolve the symlinks, as it also changes the permissions, but that did not help.

**Comment by tupakkatapa** [comment]
Got it, the paths here are wrong: https://github.com/ponkila/HomestakerOS/blob/f2ed12f0a29651b5f1a331197e54290e6f167b0c/webui/src/Context/NodeInfoContext.tsx#L33-L46

They should be: 
```
/nixosConfigurations/${hostname}/result/<filename>
```

**Comment by jormeli** [comment]
> They should be:

Good to know 👍 

As for handling arbitrary files in the result folder, the simplest option I see is to have some sort of `files.json` that describes the available files. The frontend can then read this file.

**Comment by tupakkatapa** [comment]
Closed by #27.
