### ISSUE TITLE
webui: add demo URL

### ISSUE THREAD

**Issue by jhvst** [ponkila/HomestakerOS#30]
We should have a demo URL hosted on the root domain where we have the UI as a preview but with limited functionality (no bash pipe). We should use our `homestaking-infra` repo nodes as the demo endpoints.

This could be pushed to, e.g., CloudFlare pages and can be maintained either on a separate package or in a hard-coded branch.

**Comment by jhvst** [comment]
Closed on the branch demo, which is now deployed to Vercel at least for the time being. This has a URL alias demo.homestakeros.com. This demo URL could be added to GitHub readme at some point @tupakkatapa

**Comment by tupakkatapa** [comment]
The URL in the 'About' section of this repository details should be updated. I don't have permissions to do that.
