### ISSUE TITLE
.#update-json: json file directories not automatically creates

### ISSUE THREAD

**Issue by jhvst** [ponkila/HomestakerOS#32]
If the demo branch is cloned and `nix run --no-warn-dirty .#update-json` run, the following errors appear:

```
/nix/store/1sq7czgs3x0q224jmjxf8793hic4zm49-update-json/bin/.update-json-wrapped: line 27: webui/nixosConfigurations/dinar-ephemeral-alpha/default.json: No such file or directory
/nix/store/1sq7czgs3x0q224jmjxf8793hic4zm49-update-json/bin/.update-json-wrapped: line 27: webui/nixosConfigurations/dinar-ephemeral-beta/default.json: No such file or directory
/nix/store/1sq7czgs3x0q224jmjxf8793hic4zm49-update-json/bin/.update-json-wrapped: line 27: webui/nixosConfigurations/ponkila-ephemeral-beta/default.json: No such file or directory
```

Further, no `default.json` is created. If instead the folders are created, then the file appears.

The update json script should create the folder if it does not yet exist.

**Comment by jhvst** [comment]
Further, the assets could be put directly into `webui/public` folder where they will resolve. See: https://github.com/ponkila/HomestakerOS/compare/main...demo

**Comment by tupakkatapa** [comment]
Closed by https://github.com/ponkila/HomestakerOS/commit/73296dcc68e43666106fa8b5be2003cc1967a406.
