### ISSUE TITLE
homestakeros: add bitcoind/electrs

### ISSUE THREAD

**Issue by tupakkatapa** [ponkila/HomestakerOS#57]
https://github.com/magnyon/bitcoind
https://github.com/MarinX/electrumrpc

Example: https://github.com/ponkila/homestaking-infra/blob/1e9b3409da400cc5524897306e33b9520921b756/nixosConfigurations/kaakkuri-ephemeral-alpha/default.nix

**Comment by jhvst** [comment]
This won't be needed. We run it for a very specific use-case.
