### ISSUE TITLE
webui: missing other clients

### ISSUE THREAD

**Issue by tupakkatapa** [ponkila/HomestakerOS#8]
New launchpad clients were introduced by https://github.com/ponkila/nixobolus/pull/25.

These are present in `schema.json`, however, they do not appear in the Web UI as options.

**Comment by tupakkatapa** [comment]
Option schema should currently be located at `webui/schema.json`. 

It's created by the server initializing script `, server` or just `, schema`, which runs the following command: `nix eval --json .#schema | jq > webui/schema.json`. It can be generated at the most convenient place for the front end. 

However, if you are talking about it appearing in different place right now, I have no idea what created it or why it even exists there.

**Comment by jormeli** [comment]
The frontend can only read files from `webui/public` (if running in dev mode) or `webui/dist` (if running a built version with `app.js`), so I think the `schema.json` file should be generated into the latter, or the other static folder served by `app.js` which hosts the node configurations, `hostnames.json`, etc. (currently `./nixosConfiguration`, but can be changed)

**Comment by tupakkatapa** [comment]
Feel free to change the path at which `schema.json` is generated, it should not break anything since the schema is for front end use only. 

You just need to modify the `webui/schema.json` paths at both mission-control scripts:

https://github.com/ponkila/HomestakerOS/blob/b9c380056e13ea575b3191fe216d4a0e68742ee1/flake.nix#L58-L75

**Comment by tupakkatapa** [comment]
> I think the `schema.json` file should be generated into the latter

This was kinda related in PR https://github.com/ponkila/HomestakerOS/pull/13 since I was updating the server script so I updated paths for you. ref: https://github.com/ponkila/HomestakerOS/pull/13/commits/ee0daa5023c20780c75a985bae92e27f78865291

Decided to generate the schema to `webui/public` since the `dist` directory is only available after the build which is a bit inconvenient.

**Comment by jhvst** [comment]
So the `schema.json` file should only exist in one place and the way it would be controlled is by building the package. By default (as it's in git), should tailor to development mode. Then, building the web UI with Nix would essentially copy the dist folder, and place the schema.json and other files in there. When the node code is compiled, it would pull the dist files from the UI build, and then serve those. We will probably need some flag to node, maybe something we can set as environment variable, which controls which folder it is (or is it something else).

But before Jesse has got around to packaging the web UI with Nix, then I'm open to any ad-hoc solution.

**Comment by tupakkatapa** [comment]
Closed by #16.
